# Use Nginx as a lightweight web server
FROM nginx:alpine

# Copy your index.html file into Nginx’s default web directory
COPY index.html /usr/share/nginx/html/index.html

# Tell Docker to open port 80
EXPOSE 80
